### ISSUE TITLE
Model 5 seems to downscale by 4

### ISSUE THREAD

**Issue by Memnarch** [HolyWu/vs-basicvsrpp#10]
Hi,
While I got good results, they did not seem to be quite as sharp as I expected them. When I tried to process a 136x264 Video, I suddenly got the error:

```
Traceback (most recent call last):
  File "E:\Git\RivenTools\Reproduce.py", line 26, in <module>
    video.output(f, y4m=True)
  File "src\cython\vapoursynth.pyx", line 1790, in vapoursynth.VideoNode.output
  File "src\cython\vapoursynth.pyx", line 1655, in frames
  File "D:\Program Files\Python39\lib\concurrent\futures\_base.py", line 445, in result
    return self.__get_result()
  File "D:\Program Files\Python39\lib\concurrent\futures\_base.py", line 390, in __get_result
    raise self._exception
vapoursynth.Error: The height and width of low-res inputs must be at least 64, but got 66 and 34.
```

But my Video is larger. Looking into it, executing Model 5 downscales the video. Or at least its internal data seems to be downscaled. While the returned clip reports the correct size, the frames seem to be lower. A quarter to be precise.

This seems to be the code causing it:
https://github.com/HolyWu/vs-basicvsrpp/blob/da066461f66c6e7deedf354630899b815393836b/vsbasicvsrpp/basicvsr_pp.py#L291

And this is the script to reproduce it (It's a trimmed down version, that's why model 5 and 1 are executed directly after one another. My pipeline has some steps inbetween):
[Reproduce.zip](https://github.com/HolyWu/vs-basicvsrpp/files/7274531/Reproduce.zip)

If you need that specific video from my script, I can share that with you but would prefer to do that outside of this report, as it's a game asset.

**Comment by HolyWu** [comment]
Yes, it's by design for model 3-5 as the code you linked. That's why [input resolution must be at least 256 and mod-4 for model 3-5](https://github.com/HolyWu/vs-basicvsrpp/blob/da066461f66c6e7deedf354630899b815393836b/vsbasicvsrpp/__init__.py#L23).

**Comment by Memnarch** [comment]
I was not able to find that in the original mmediting-code. Their documentation says
"is_low_res_input (bool, optional): Whether the input is low-resolution
or not. If False, the output resolution is equal to the input"
However in this case, the output-resolution is smaller than the input resolution.
