### ISSUE TITLE
Question about the tiling,...

### ISSUE THREAD

**Issue by Selur** [HolyWu/vs-basicvsrpp#12]
I got a Geforce GTX 1070ti with 8 GB of vram. (I know it's not new and really that suited for this, but that's what I got. :))
If I crop my source to a 480x480 chunk and run BasicVSR++ on it ~1.4-3.5GB VRAM are used.
Not cropping my source, I thought that even with some padding I thought that using "BasicVSRPP(clip=clip, model=5, tile_x=480, tile_y=480)" would allow me to filter HD an UHD clips which it does not.
Question is: Why? Shouldn't this work with a 480x480 tiling?

What are the min tile with and height sizes (I assumed it would be 64*4=256 + padding, but when using 320x320 I get: 
`Python exception: Analyse: failed to retrieve first frame from super clip. Error message: The height and width of low-res inputs must be at least 64, but got 84 and 44.`
Using 392x392 I get `The height and width of low-res inputs must be at least 64, but got 102 and 26.`
->Just from testing I don't get what the tiling does at all. :)

**Comment by HolyWu** [comment]
What's the original resolution of your source?
