### ISSUE TITLE
NTIRE 2021 Video Super-Resolution

### ISSUE THREAD

**Issue by AIisCool** [HolyWu/vs-basicvsrpp#19]
Hello again HolyWu!

If I am not mistaken there is a new model "[NTIRE 2021 Video Super-Resolution](https://download.openmmlab.com/mmediting/restorers/basicvsr_plusplus/basicvsr_plusplus_c128n25_ntire_vsr_20210311-1ff35292.pth)" under [NTIRE 2021 checkpoints](https://github.com/open-mmlab/mmediting/blob/master/configs/restorers/basicvsr_plusplus/README.md) that isn't included in this port?

Would it be possible to add it? Thank you and happy holidays.

**Comment by HolyWu** [comment]
No. That model is trained on REDS dataset and does not really gives pleasing visual results to me.
