### ISSUE TITLE
ModulatedDeformConv is not implemented on CPU

### ISSUE THREAD

**Issue by Selur** [HolyWu/vs-basicvsrpp#2]
When using:
```
clip = BasicVSRPP(clip=clip, model=1, device_type="cpu")
```
I get: `ModulatedDeformConv is not implemented on CPU`

Cu Selur

**Comment by HolyWu** [comment]
Apparently the required module is only implemented on GPU in MMCV. Guess I'd better remove the device_type parameter since it's useless.

**Comment by Selur** [comment]
Okay, thanks. (happy to know that it's not something I forgot to install or similar ;))
