### ISSUE TITLE
Sizes of tensors must match except in dimension 3. Got 213 and 214 (The offending index is 0)

### ISSUE THREAD

**Issue by oblessnoob** [HolyWu/vs-basicvsrpp#20]
python 3.9.7
torch 1.9.1
mmcv 1.3.13/1.4.4
vs r57
vs fatpack

import vapoursynth as vs
core = vs.core

from vsbasicvsrpp import BasicVSRPP

video = core.ffms2.Source(source=r'D:\winpython\VapourSynth64Portable\in.mp4')

video = core.resize.Bicubic(clip=video, format=vs.RGBS, matrix_in_s="709")

video = BasicVSRPP(clip=video, interval=10, model=5, fp16=True, tile_pad=0)

video = core.resize.Bicubic(video, format=vs.YUV420P8, matrix_s="709")

video.set_output()

**Comment by HolyWu** [comment]
Is the video's resolution mod-4? See https://github.com/HolyWu/vs-basicvsrpp/blob/00761587db4f2c755c979a87e1be188531263841/vsbasicvsrpp/__init__.py#L23.

**Comment by oblessnoob** [comment]
Thanks, solved with std.AddBorders and std.Crop
