### ISSUE TITLE
Building wheel for mmcv-full (setup.py) ... error

### ISSUE THREAD

**Issue by xiaomingxige** [HolyWu/vs-basicvsrpp#22]

**Comment by xiaomingxige** [comment]
error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
  ----------------------------------------
  ERROR: Failed building wheel for mmcv-full

**Comment by HolyWu** [comment]
MMCV has pre-built packages for Linux so you shouldn't need to build it. See the table below https://github.com/open-mmlab/mmcv#installation.
