### ISSUE TITLE
mmcv-full on Windows and Python 3.10

### ISSUE THREAD

**Issue by Selur** [HolyWu/vs-basicvsrpp#23]
Since Vapoursynth RC58 either need Python 3.8 (Win7 compatible) or Python 3.10 (which I'm using), the current mmcv_full-1.3.16-cp39-cp39-win_amd64.whl is not a supported wheel since it's meant for Python 3.9.
Would be nice if you could create a mmcv-full for Python 3.10 in Windows.
Thanks!

**Comment by HolyWu** [comment]
MMCV has officially provided the mmcv-full pre-built packages on Windows since v1.4.0. See https://github.com/open-mmlab/mmcv/releases and the table below https://github.com/open-mmlab/mmcv#installation.

**Comment by Selur** [comment]
Thanks! Didn't know that.
It worked nicely.
Using: 
```
pip install mmcv-full -f https://download.openmmlab.com/mmcv/dist/cu113/torch1.11/index.html
pip install tqdm
pip install opencv-python
python -m pip install --upgrade vsbasicvsrpp
python -m vsbasicvsrpp
````
I could get vs-basicvrpp working with Vapoursynth RC58 and Python 3.10!

Thanks!
