### ISSUE TITLE
Conflicts with vs-dpir

### ISSUE THREAD

**Issue by banjaminicc** [HolyWu/vs-basicvsrpp#32]
```
from vsdpir import dpir
from vsbasicvsrpp import basicvsrpp
```
importing like this breaks without error

```
from vsbasicvsrpp import basicvsrpp
from vsdpir import dpir
```
This throws the error : 
```
The procedure entry point cublasLt_for_cublas_TST could not be located in the dynamic link library D:\Programmes\CUDA\bin\cublas64_11.dll. 
```
While just importing vsdpir and just importing basicvsrpp works just fine.

**Comment by HolyWu** [comment]
https://github.com/HomeOfVapourSynthEvolution/VapourSynth-DFTTest doesn't have DFTTest2. Are you referring to https://github.com/AmusementClub/vs-dfttest2?
