### ISSUE TITLE
mmcv 2.0 support

### ISSUE THREAD

**Issue by soldivelot** [HolyWu/vs-basicvsrpp#33]
any plan to support mmcv 2.0? thx.

**Comment by HolyWu** [comment]
I'm afraid that I won't add support for it unless the author of https://github.com/ckkelvinchan/BasicVSR_PlusPlus will adapt his code to MMCV 2.0. The API changes too much between 1.0 and 2.0 and I don't plan to spend time on studying its documents and modify the codes.
