### ISSUE TITLE
Pretrained models are missing from the repository

### ISSUE THREAD

**Issue by Memnarch** [HolyWu/vs-basicvsrpp#5]
Hi,
I noticed that the pth files have a size of 0. Is a dev suposed to add the missing one or should they exist in this repo?

**Comment by Memnarch** [comment]
they exist as download resource on the releases

**Comment by HolyWu** [comment]
Actually there is a second step in https://github.com/HolyWu/vs-basicvsrpp#installation (`python -m vsbasicvsrpp`) to download the model files for the users.

**Comment by Memnarch** [comment]
Ah I see! I had to redo my Python environment at one point and probably forgot it the second time.
